### PR TITLE
Update CI test environment

### PR DESCRIPTION
**Pull request by kilchenmann**
Resolves [DSP-409](https://dasch.myjetbrains.com/youtrack/issue/DSP-409)

### CODE REVIEW

**Comment by kilchenmann** [comment]
> I've added the secrets.

Great thanks.

**Comment by kilchenmann** [comment]
@subotic Do we have to rename the knora-app image on docker-hub. I already renamed it here in the workflow...

**Comment by subotic** [comment]
@kilchenmann Docker Hub repositories cannot be renamed. You (or I) will need to create a new repository with the new name.

**Comment by subotic** [comment]
@kilchenmann I've created the repository on Dockerhub.

**Comment by kilchenmann** [comment]
Creating new is anyway the better solution. Thanks for the new repo on docker-hub.

**Pull request merged**
