### PR TITLE
feat(ontology): default language for property label

### PR DESCRIPTION
**Pull request by kilchenmann**
resolves DSP-1346

In this PR I implemented a select form element to select one default language for the property label.

### CODE REVIEW

**Review by flavens — CHANGES_REQUESTED** [review]
On my screen, the field label is cropped.. It may be too long as well.

Screenshot 2021-02-16 at 16 48 04

And when I update the corresponding props in English first and then I open again the edit form and change the language to Deutsch. How do I know in which language is my props, is there a mix? If a user wants to enter the props in 2 languages, can s.he do that? If yes, it is not clear to me.

**Comment by kilchenmann** [comment]
> On my screen, the field label is cropped.. It may be too long as well.

What do you mean "it's cropped"?

> 
> And when I update the corresponding props in English first and then I open again the edit form and change the language to Deutsch. How do I know in which language is my props, is there a mix? If a user wants to enter the props in 2 languages, can s.he do that? If yes, it is not clear to me.

Yes you're right it's not clear. It's a first try and has to be well documented, but it has to be improved too. In this first version of ontology editor you have to select one language for all properties. You can add more labels in other languages later in the edit property part (this is another branch I'm working on). But for now this is a fast solution to create properties with a language.

**Comment by kilchenmann** [comment]
In my version it's not cropped

Screen Shot 2021-02-16 at 17 09 42

**Comment by kilchenmann** [comment]
> On my screen, the field label is cropped.. It may be too long as well.

Shortened the placeholder in e5b5a94

**Review by flavens — APPROVED** [review]
The language selector issue should be improved quite soon because even disabled, I am not that a user will understand the situation...

**Comment by kilchenmann** [comment]
> The language selector issue should be improved quite soon because even disabled, I am not that a user will understand the situation...

I totally agree and I'm open for better solutions!

Thanks for approving 🎉

**Pull request merged**
