### PR TITLE
refactor: openseadragon prod build fix (DSP-1779)

### PR DESCRIPTION
**Pull request by mdelez**
resolves DSP-1779

### CODE REVIEW

**Review by kilchenmann — APPROVED** [review]
wow! LGTM. Let's try....

**Comment by EricSommerhalder** [comment]
Looks good to me as well. I feel like we should document somewhere that we only support rectangular regions at the moment though. I'm not sure where.

**Review by EricSommerhalder — APPROVED** [review]

**Comment by mdelez** [comment]
> Looks good to me as well. I feel like we should document somewhere that we only support rectangular regions at the moment though. I'm not sure where.

Yeah, that's a good point. I'll check the docs and see if they can be updated.

**Comment by kilchenmann** [comment]
> > Looks good to me as well. I feel like we should document somewhere that we only support rectangular regions at the moment though. I'm not sure where.
> 
> Yeah, that's a good point. I'll check the docs and see if they can be updated.

The whole part about "Working with resources" is not yet written (or only partial). Here's the (data) [user guide](https://docs.dasch.swiss/DSP-APP/user-guide/data/) which has the be improved completely.

**Pull request merged**
