### PR TITLE
feat(resource): update resource's label (DSP-1801)

### PR DESCRIPTION
**Pull request by kilchenmann**
resolves DSP-1801

### CODE REVIEW

**Comment by kilchenmann** [comment]
There are two issues which can't be resolved right now. Both are described in the Youtrack's task:

- <https://dasch.myjetbrains.com/youtrack/issue/DSP-1801#focus=Comments-4-3279.0-0>
- <https://dasch.myjetbrains.com/youtrack/issue/DSP-1801#focus=Comments-4-3280.0-0>

**Comment by kilchenmann** [comment]
@mdelez what should we do with the two issues mentioned in previous comment? In second case it needs an update of the API or should I do a second request to get the necessary information? Any suggestions?

**Comment by kilchenmann** [comment]
This is the first iteration. It has to be improved as soon as DSP-API resolved the "update metadata" response. At the moment it's not possible to edit the label twice without refreshing the whole page. 
For the moment we can't wait for new release of DSP-API because this will be v14.0.0 which contains a lot of breaking changes.

**Review by mdelez — APPROVED** [review]
looks good :)

**Pull request merged**
