### PR TITLE
DSP-284 Display app version in header

### PR DESCRIPTION
**Pull request by kilchenmann**
resolves [DSP-284](https://dasch.myjetbrains.com/youtrack/issue/DSP-284)

### CODE REVIEW

**Review by flavens — COMMENTED** [review]
It looks good on a desktop screen. However, in a tablet and phone screens, it overlaps the app name.
PS: in a tablet screen, both full and cropped app names are displayed...

**Comment by kilchenmann** [comment]
> It looks good on a desktop screen. However, in a tablet and phone screens, it overlaps the app name.
> PS: in a tablet screen, both full and cropped app names are displayed...

I see. I will refactor it now...

**Comment by kilchenmann** [comment]
The issue with responsive logo should be fixed. With the version "0.0.0-PLACEHOLDER" in development version it's way too long of course. With the longest version number e.g. "3.0.0-rc.12" it could look as follow:

Screenshot 2020-09-28 at 09 31 07

**Review by flavens — APPROVED** [review]
LGTM! thanks

**Pull request merged**
