### PR TITLE
feat(ontology): support partOf value to create book res class (DEV-180)

### PR DESCRIPTION
**Pull request by kilchenmann**
resolves DEV-180

### CODE REVIEW

**Comment by kilchenmann** [comment]
we have to wait for new API release with fixed bug <https://github.com/dasch-swiss/dsp-api/pull/1978>

**Comment by kilchenmann** [comment]
@mdelez you'll need latest release of DSP-API (or main branch) if you want to test this feature. Please feel free to correct the new section in the documentation.

**Review by mdelez — APPROVED** [review]
Works well for me!

**Comment by kilchenmann** [comment]
Thank you @mdelez for updating the docs

**Pull request merged**
