### PR TITLE
Simple ontology creator

### LINKED ISSUE #63: Add resource classes in ontology editor

### LINKED ISSUE #64: Ontology Editor
Implement the ontology editor. 
To create an ontology, add resources classes, add properties to a class, edit.

### LINKED ISSUE #65: Add properties to a class in ontology editor

### PR DESCRIPTION
**Pull request by kilchenmann**
This PR implements the ontology part into admin/project. It has a dependency to the unpublished knora-ui core module on branch [wip/ontology-service](https://github.com/dasch-swiss/knora-ui/tree/master) ~~([PR #400](https://github.com/dasch-swiss/knora-ui/pull/400))~~.

closes #64 

- [x] List of project ontologies
- [x] Form to create / add new ontology
- [x] List of resource classes in ontology view
  - [ ] ~~Use a visual graph tool: d3js~~ &rarr; postponed #238 
- [x] Add resource class to ontology; closes #63 
- [x] Add property to class; closes #65 
  - [x] Label
  - [x] Type incl. Gui-ele
  - [x] Gui attributes in case of lists and resource pointer
  - [x] Cardinality
  - [ ] ~~Permission~~ --> this will be part of another task 
  - [x] GUI order (drag'n'drop)

### CODE REVIEW

**Comment by flavens** [comment]
@kilchenmann I am not able to run locally this branch. Could you add all the settings and branch name from all the dependencies we have to use (knora-ui, knora-api-js-lib, knora-api)?

**Comment by kilchenmann** [comment]
> I am not able to run locally this branch

@flavens I will have a look on that... probably we should sit together. I have no idea where it fails.

**Comment by kilchenmann** [comment]
@flavens You need @knora/core from knora-ui branch [wip/ontology-service](https://github.com/dasch-swiss/knora-ui/tree/wip/ontology-service). Build it with yalc and add it to the app. And it should run with the latest develop version from knora-api.

**Comment by kilchenmann** [comment]
@flavens Not sure if it's ready now, but we should sit together and talk about the names / placeholders and the ontology creation workflow.

**Before merging**: This PR needs a new version of @knora/core (s. [wip/ontology-service](https://github.com/dasch-swiss/knora-ui/tree/wip/ontology-service). The tests are running because of a yalc "hack". The part with yalc should be removed from [.travis.yml](https://github.com/dasch-swiss/knora-app/blob/wip/simple-ontology-creator/.travis.yml) and [.circleci/config.yml](https://github.com/dasch-swiss/knora-app/blob/wip/simple-ontology-creator/.circleci/config.yml) before merging!!!

**Comment by kilchenmann** [comment]
Reuse existing properties doesn't work as expected. For example:
Two resource classes (movie and image), both have a property called `title` and I wanted to reuse the same property definitions (label, gui-element, subclass and gui-attribute) but I get the following error response from knora-api:

```
{"knora-api:error":"org.knora.webapi.BadRequestException: Class http://0.0.0.0:3333/ontology/0001/notizblogg/v2#notv4s22mkujtim has a cardinality for property http://0.0.0.0:3333/ontology/0001/notizblogg/v2#nothgor5vcyd78h, but is not a subclass of that property's http://api.knora.org/ontology/knora-api/v2#subjectType, http://0.0.0.0:3333/ontology/0001/notizblogg/v2#not09axt7jmocxn","@context":{"knora-api":"http://api.knora.org/ontology/knora-api/v2#"}}
```

So I have to undo the work already done.

**Comment by kilchenmann** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DaSCH/Kuirl/pullRequest?prid=4776495&bid=15912417)

**Comment by kilchenmann** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DaSCH/Kuirl/pullRequest?prid=4776495&bid=15912417)

**Comment by kilchenmann** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 7
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/DaSCH/Kuirl/pullRequest?prid=4776495&bid=15912417)

**Comment by kilchenmann** [comment]
The ontology editor is still work in progress and needs some improvements. But we should split these tasks into smaller PRs

**Comment by SepidehAlassi** [comment]
> Information for the reviewers @flavens @SepidehAlassi:
> The ontology editor is still work in progress and needs some improvements. But we should split these tasks into smaller PRs and merge this PR asap. Right now I'm not able to work more on it...

@kilchenmann I will review this first thing tomorrow.

**Comment by SepidehAlassi** [comment]
To test that basic functionalities are there, I added a new ontology and added a new resource class, and tried adding a new property with text value, this failed with errors. Please see below:
Screenshot 2020-08-20 at 13 14 46

Is this a known problem and is supposed to be fixed in another PR?

**Review by SepidehAlassi — CHANGES_REQUESTED** [review]
To test that basic functionalities are there, I added a new ontology and added a new resource class, and then tried adding a new property with a text value. This failed with errors. Please see below:
Screenshot 2020-08-20 at 13 14 46

Is this a known problem and is supposed to be fixed in another PR? If so, can you please make a user story about it?

**Comment by kilchenmann** [comment]
> Is this a known problem and is supposed to be fixed in another PR?

Yes this is a known issue because of the missing method `createClassProperty` in js-lib. For the missing method I already have a user story, but not yet for the issues in this PR. I didn't had the time yet to write them down but will do asap.

**Review by SepidehAlassi — APPROVED** [review]
Then please go ahead and merge this PR.

**Pull request merged**
