### PR TITLE
feat(ontology): new method to change gui order (DSP-1567/DSP-1646)

### PR DESCRIPTION
**Pull request by kilchenmann**
resolves DSP-1567 and DSP-1646

~~This PR contains a quick solution to solve our update-gui-order-issue in case if the property is already in use (DSP-1546). Since we have two DSP-API routes to change either the cardinality or the gui-order, we should also split those tasks into different views in DSP-APP. This step will take more time and we have to fix the current state on our servers now. The current solution is as follow: We send to request to DSP-API: one to update the gui-order and one to update the cardinalities. The second request will throw always an error if the property is in use and has already data values. There's another workaround for that issue, but it's not yet published in DSP-API. So for now, I suggest to keep this "ugly" solution.~~

### CODE REVIEW

**Review by flavens — CHANGES_REQUESTED** [review]
I cannot update the prop field form, I tried with 2 versions of dsp-api (see screen shots):

v13.6.0
Screenshot 2021-05-17 at 10 19 01

v13.7.0
Screenshot 2021-05-17 at 10 36 07

here is the network preview log: 

"knora-api:error: "org.knora.webapi.exceptions.BadRequestException: One or more submitted properties do not have cardinalities in class http://0.0.0.0:3333/ontology/0001/anything/v2#BlueThing: http://0.0.0.0:3333/ontology/0001/anything/v2#hasGeoname, http://0.0.0.0:3333/ontology/0001/anything/v2#hasInteger, http://0.0.0.0:3333/ontology/0001/anything/v2#isPartOfOtherThing, http://0.0.0.0:3333/ontology/0001/anything/v2#hasRichtext, http://0.0.0.0:3333/ontology/0001/anything/v2#hasOtherListItem, http://0.0.0.0:3333/ontology/0001/anything/v2#hasDate, http://0.0.0.0:3333/ontology/0001/anything/v2#hasColor, http://0.0.0.0:3333/ontology/0001/anything/v2#hasThingDocument, http://0.0.0.0:3333/ontology/0001/anything/v2#hasListItem, http://0.0.0.0:3333/ontology/0001/anything/v2#hasBoolean, http://0.0.0.0:3333/ontology/0001/anything/v2#hasDecimal, http://0.0.0.0:3333/ontology/0001/anything/v2#hasGeometry, http://0.0.0.0:3333/ontology/0001/anything/v2#hasText, http://0.0.0.0:3333/ontology/0001/anything/v2#hasThingPicture, http://0.0.0.0:3333/ontology/0001/anything/v2#hasInterval, http://0.0.0.0:3333/ontology/0001/anything/v2#hasUri, http://0.0.0.0:3333/ontology/0001/anything/v2#hasTimeStamp""

did I miss something?

**Comment by kilchenmann** [comment]
@flavens You'll need at least DSP-API v13.7.0

**Comment by flavens** [comment]
> @flavens You'll need at least DSP-API v13.7.0 (with the new route to update the gui-order https://github.com/dasch-swiss/dsp-api/releases/tag/v13.7.0)
> 
> It's hard to say what was going wrong here. What's the message in the API error response of:

With the anything ontology, the API response has been quoted in my message from the network tab. There is no more details in the console.

**Comment by kilchenmann** [comment]
> > @flavens You'll need at least DSP-API v13.7.0 (with the new route to update the gui-order https://github.com/dasch-swiss/dsp-api/releases/tag/v13.7.0)
> > It's hard to say what was going wrong here. What's the message in the API error response of:
> 
> With the anything ontology, the API response has been quoted in my message from the network tab. There is no more details in the console.

Not in the console, but in the network...

But I will also check-out this branch again. At the moment I'm working with the region-annotation-branch

**Comment by kilchenmann** [comment]
There are several issues and I couldn't find a quick solution to keep the current implementation (s. my comment on Youtrack DSP-1567). I will separate the two requests now.

**Comment by kilchenmann** [comment]
As mentioned in one of the Youtrack issues, it was not possible to keep the current setup to change the gui-order of properties in a resource class. So I implemented a new way to change the gui-order (DSP-1646):


https://user-images.githubusercontent.com/4253580/118961965-2d6ebe80-b965-11eb-87e4-47a97a34890d.mov

**Comment by kilchenmann** [comment]
@mdelez @waychal @lrosenth now it should be ready for the review

**Review by mdelez — APPROVED** [review]

**Pull request merged**
